### ISSUE TITLE
Please provide a method to create an unbounded LruCache

### ISSUE THREAD

**Issue by joshtriplett** [kyren/hashlink#2]
The `new` method expects a capacity. Sometimes you want to manage the cache some other way, and manually call `remove_lru` to prune items. For such cases, could you please provide an `LruCache::new_unbounded()` method, to create an `LruCache` without a capacity limit?

**Comment by kyren** [comment]
That's a really good suggestion!

**Comment by kyren** [comment]
Actually, hmmm just to make sure I've thought it through, let me bounce some ideas off you...

First, having an `LruCache` with an unbounded capacity is mostly the same as having a plain `LinkedHashMap`.  I still think it's probably reasonable to want the option of having an unlimited `LruCache`, but I just wanted to make sure you were aware that there's a solution already.  (You probably already knew this, sorry!)

Second, assuming we want this on `LruCache`, should there be something like an `Option<usize>` for the capacity, or would it suffice to just make `LruCache::new_unbounded()` simply an alias for `LruCache::new(usize::MAX)`?  Is that what you were suggesting?  I don't really think `Option<usize>` is meaningfully better than just `usize::MAX` here.

**Comment by kyren** [comment]
I went ahead and added `LruCache::unbounded` and some other convenience methods from the `lru` crate in 1d0aa552f321ca56956f31068a38939a11f9e551.  `unbounded` works like I said, it simply sets the capacity to `usize::MAX` (just like the in the `lru` crate).

**Comment by joshtriplett** [comment]
As far as I can tell, using a plain `LinkedHashMap` as an unbounded LRU cache would require manually implementing the LRU behavior, whereas `LruCache` automatically reorders entries when you call `get` and similar. So yes, I think there's value in an unbounded `LruCache`.

A bound of `usize::MAX` seems fine.

**Comment by kyren** [comment]
> As far as I can tell, using a plain LinkedHashMap as an unbounded LRU cache would require manually implementing the LRU behavior, whereas LruCache automatically reorders entries when you call get and similar. So yes, I think there's value in an unbounded LruCache.

Yeah makes sense, it's added now 👍 

> A bound of usize::MAX seems fine, except that if new optimizes by preallocating for the expected capacity, new_unbounded must not attempt to preallocate for a capacity of usize::MAX.

`LruCache::new` doesn't preallocate currently, but I'll make sure to watch out for that.

**Comment by kyren** [comment]
Released hashlink 0.5.1 with these changes!

**Comment by joshtriplett** [comment]
@kyren Thanks!
